version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: hoopsprospect_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: myMasterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  postgres_data:
  meili_data:
